scan_type:
    - MRI
    - PET
    - CT
    - meeg
    - behavioral
    - microscopy
    - NIRS
    - motion
data_type:
    - anat
    - func
    - dwi
    - perf
    - pet
    - ct
    - eeg
    - ieeg
    - rns
    - scalp eeg
    - meg
    - beh
    - micr
    - nirs
    - motion
modality:
    - FLAIR
    - MEMP2RAGE
    - T1w
    - T2star
    - T2w
    - bold
    - dwi
    - pet
    - scout
task:
    - task-audio
    - task-object
    - task-picnaming
    - task-rest
    - task-rhyming
    - task-scenemem
    - task-sentence
    - task-verbgen
    - task-wordgen
    - task?
ce:
    - ce-gad
acq:
    - acq-1mm_v1_inv1
    - acq-1mm_v1_inv1_nd
    - acq-1mm_v1_inv1_nd_rms
    - acq-1mm_v1_inv1_rms
    - acq-1mm_v1_inv2
    - acq-1mm_v1_inv2_nd
    - acq-1mm_v1_inv2_nd_rms
    - acq-1mm_v1_inv2_rms
    - acq-1mm_v1_uni_images
    - acq-1mm_v1_uni_images_nd
    - acq-1mm_v1_uni_images_nd_rms
    - acq-1mm_v1_uni_images_rms
    - acq-1mm_v2_inv1
    - acq-1mm_v2_inv1_rms
    - acq-1mm_v2_inv2
    - acq-1mm_v2_inv2_rms
    - acq-1mm_v2_t1_images
    - acq-1mm_v2_uni_images
    - acq-1mm_v2_uni_images_rms
    - acq-2d_0_25x0_25x2_0mm_p1
    - acq-2d_0_25x0_25x2_0mm_p2
    - acq-2d_0_4x0_4x1_2mm_180flip
    - acq-2d_0_8x0_8x5mm_5nex_nsir_hippo_290v_inv1
    - acq-2d_0_8x0_8x5mm_5nex_nsir_hippo_290v_inv2
    - acq-2d_0_8x0_8x5mm_5nex_nsir_hippo_290v_t1_images
    - acq-2d_0_8x0_8x5mm_5nex_nsir_hippo_290v_uni_images
    - acq-3pl_fgre
    - acq-64ch_head_coil
    - acq-T2_tirm_tra
    - acq-adc
    - acq-ax
    - acq-ax_1_burn
    - acq-ax_2d
    - acq-ax_2d_resolve_adc
    - acq-ax_2d_resolve_tracew
    - acq-ax_3D_mprage
    - acq-ax_3D_stealth
    - acq-ax_3d
    - acq-ax_3d_mprage
    - acq-ax_3d_tera
    - acq-ax_adc
    - acq-ax_exp
    - acq-ax_frfse
    - acq-ax_gre
    - acq-ax_gre_hemo
    - acq-ax_haste
    - acq-ax_mpr
    - acq-ax_mprage
    - acq-ax_mprage_ipat
    - acq-ax_mprage_isotropic
    - acq-ax_propeller
    - acq-ax_resolve_adc
    - acq-ax_resolve_tracew
    - acq-ax_se
    - acq-ax_stealth
    - acq-ax_t1
    - acq-ax_t2
    - acq-ax_t2_(please_keep_at_60_slices_)
    - acq-ax_t2_2d
    - acq-ax_t2_blade
    - acq-ax_t2_nd
    - acq-ax_t2_optimized
    - acq-ax_t2_tera
    - acq-ax_tracew
    - acq-ax_tse
    - acq-ax_tse_zz
    - acq-ax_zz
    - acq-cor
    - acq-cor2_se
    - acq-cor_2_burn
    - acq-cor_2d_3mm
    - acq-cor_2d_high_res
    - acq-cor_3d
    - acq-cor_fs
    - acq-cor_fspgr_3d
    - acq-cor_high_res
    - acq-cor_hr
    - acq-cor_ir
    - acq-cor_longtr
    - acq-cor_mpr
    - acq-cor_mpr_64ch_head_coil
    - acq-cor_mpr_recon
    - acq-cor_mprage
    - acq-cor_mprage_3d_zz
    - acq-cor_obl
    - acq-cor_p2_0_4x0_4x1_0mm
    - acq-cor_recon
    - acq-cor_se
    - acq-cor_se_zz
    - acq-cor_t1
    - acq-cor_t2
    - acq-cor_t2_3mm
    - acq-cor_t2_thin
    - acq-cor_t2_whole_brain
    - acq-cor_thin
    - acq-cor_tir
    - acq-cor_tru_ir
    - acq-cor_true_ir
    - acq-cor_tse_384_3mm_high_res
    - acq-cor_tse_hippo
    - acq-cor_zz
    - acq-fibers
    - acq-iso_1_0_p2_tra_mprage
    - acq-mark_p3_0_8mm
    - acq-mpr
    - acq-mprage_1x1x1
    - acq-mprage_1x1x1_isotropic
    - acq-mprage_p2_1mm
    - acq-mri_coregistration
    - acq-obl_hippo
    - acq-og
    - acq-p2035s0_clf17179_pass1_reccln
    - acq-p2035s0_clf17179p2_pass2
    - acq-sag
    - acq-sag2_se
    - acq-sag3_se
    - acq-sag_1_burn
    - acq-sag_3d_t2_cube
    - acq-sag_br_ctac
    - acq-sag_ffe
    - acq-sag_fse
    - acq-sag_iso_mprage
    - acq-sag_mpr
    - acq-sag_mpr_3d
    - acq-sag_mpr_64ch_head_coil
    - acq-sag_mpr_recon
    - acq-sag_mprage
    - acq-sag_mprage_iso
    - acq-sag_naims_caipi_4
    - acq-sag_recon
    - acq-sag_se
    - acq-sag_se_zz
    - acq-sag_space
    - acq-sag_spge
    - acq-sag_spgr
    - acq-sag_t1
    - acq-se
    - acq-se_laser_a_ax
    - acq-se_laser_a_cor
    - acq-se_laser_h_ax
    - acq-se_laser_h_sag
    - acq-se_other_plane
    - acq-se_other_plane_ax
    - acq-se_other_plane_sag
    - acq-siemens_ipat3_1mm_inv1
    - acq-siemens_ipat3_1mm_inv1_nd
    - acq-siemens_ipat3_1mm_inv2
    - acq-siemens_ipat3_1mm_inv2_nd
    - acq-siemens_ipat3_1mm_t1_images
    - acq-siemens_ipat3_1mm_t1_images_nd
    - acq-siemens_ipat3_1mm_uni_images
    - acq-siemens_ipat3_1mm_uni_images_nd
    - acq-spc
    - acq-tra
    - acq-tra_brainstem
    - acq-tra_mpr
    - acq-tra_mpr_64ch_head_coil
    - acq-tse
    - dose_report
    - localizer
    - siemens